---
title: Does Choice Architecture Imply Accountability Architecture? Experimental Evidence
  of Individuals' Ability to Hold Policymakers Accountable for Nudges Gone Wrong
output: pdf_document
bibliography: Bibliography.bib
---

#Section I: Introduction

Critics frequently argue that nudges are more covert, less transparent, and more difficult to monitor than traditional regulatory tools. Edward Glaeser, for example, argues that "[p]ublic monitoring of soft paternalism is much more difficult than public monitoring of hard paternalism." [@Glaeser2006b, p. 151] As one of the leading proponents of soft paternalism, Cass Sunstein, acknowledges, while "[m]andates and commands are highly visible," [@Sunstein2013, p. 1890] "[soft] paternalism --- and some nudges in particular --- may be invisible." [@Sunstein2013, p. 1892] "The public can observe the size of sin taxes and voters can tell that certain activities have been outlawed," [@Glaeser2006b, p. 151] but nudges often "appear to be invisible." [@Sunstein2013b, p. 3].

To many, this lack of transparency is feature of soft paternalism, not a bug. Soft paternalism leverages individual cognitive biases to produce outcomes that approximate those achieved by a completely informed, rational decision-maker. [@Sunstein2013] Many of such interventions operate by altering the *salience* of some feature of a decision-making environment. For example, if foods in a cafeteria line placed at eye level are more likely to be purchased than foods placed at waist level, soft paternalism recommends placing healthy foods where they are most easily seen. However, individuals "often correct against bias when they become aware of it." [@Calo2014, p. 795] Thus, the fact that the regulatory intervention calls for altering the "choice environment" (in this case, the cafeteria line) so as to diminish the salience of the unhealthy food is typically *not* rendered salient to those in line. "Covertness," therefore, "is a feature of particular nudges," including "those that affect unconscious processing." [@Sunstein2014, p. 3] In short, "[s]ome of [soft] paternalism’s most celebrated techniques may not work very well were they known to those on the receiving end." [@Calo2014, p. 795]

Soft paternalism's lack of transparency, critics argue, undermines its very promise. Soft paternalism is *soft* because it imposes trivial costs on those who seek to avoid the regulatory scheme. It offers "an option to resist." [@Calo2014, p. 795] Yet if the intervention is unperceived, as a practical matter resistance is unlikely. Further, this lack of transparency creates accountability problems. Glaeser argues that the lack of transparency assocaited with soft paternalism makes it "intrinsically difficult to control and ... at least on these grounds, more subject to abuse than hard paternalism." [@Glaeser2006b, p. 151] Ryan Calo argues that soft paternalism may "reduce in citizens even the habit or instinct of thinking and choosing for themselves." [@Calo2014, p. 795] As a result, regulators may over time come to control more areas of life while facing less and less resistance, effectively "sidestepping political and judicial process." *Id.*

In response to this challenge, proponents of nudging argue that invisibility for any given individual in a particular choice environment is compatible with "careful public scrutiny" of the nudge. [@Sunstein2013, p. 1893] That is, invisibility for individuals acting within a choice environment is compatible with high salience for the public scrutinizing the intervention at a distance. As Sunstein points out, graphic images on cigarette packing, and prominently displayed fuel economy labels, for example, "received considerable public scrutiny and attention." [@Sunstein2013, p. 1893] Regulators don't control the news cycle or the public's attention; they can't guarantee that all nudges will receive attention. However, Sunstein argues that regulators can follow John Rawls' "publicity principle," which "bans government from selecting a policy that it would not be able or willing to defend publicly to its own citizens." [@Thaler2008, p. 244] So, for instance, "if government officials use cleverly worded signs to help reduce litter ... they should be happy to reveal both their methods and their motives." [@Thaler2008, p. 244] Against charges that nudges lack transparency and produce unaccountable regulators, proponents argue that nudges should be "visible, scrutinized, and monitored" by the public at large [@Sunstein2013, p. 1892]

Sunstein and Thaler's proposed solution to problem of holding regulators using nudges accountable is modeled on the same institutional design used to hold officials accountable for hard paternalism. This institutional design is nothing if not familiar. [@Ferejohn1986] It is often referred to as "democratic" oversight [@Wiener2011] or "retrospective" oversight. [@Ferejohn1986] Retrospective oversight assumes that (1) public visibility of regulation allows for (2) public scrutiny and blame and (3) political monitoring and sanction. If the public deems regulations unacceptable, "[p]olitical safeguards are triggered ... the government must defend itself publicly[,] ... [a]nd if the public defense is perceived as weak, the proposed action may well crumble." [@Sunstein2013, p. 1980]

This solution to soft paternalism's accountability problem --- importing the traditional command and control accountability architecture --- rests on an important assumption: that retrospective oversights works as well with nudges as it does with hard paternalism. More technically, it assumes that publicizing nudges renders individuals at least *as capable* of scrutinizing nudges as they are capable of scrutinizing traditional command and control legislation. Indeed, both parties to the debate appear to assume as much: so long as nudges are transparent, regulators can be held accountable via democratic oversight. The point of contention is whether nudges are, in fact, transparent, and, if not, how they can be made so. Both sides agree that if nudges are sufficiently visible, individuals will be at least as capable of scrutinizing nudges as they are capable of scrutinizing traditional command and control legislation. This paper tests that assumption. 

Section II of the paper situates nudges within the broader context of regulatory “mechanism choice.” It highlights that fact that nudges must balance efficiency with accountability. Because accountability is an important regulatory value – considered, among other things, in judicial analyses and regulatory impact analyses - it is natural to suggest that regulators trade some efficiency for accountability. Since soft paternalism is a relatively new regulatory tool, regulators and advocates have focused primarily on establishing the efficiency of nudges and thought less of how we hold regulators accountable for “nudges gone wrong.”

To begin to remedy this deficiency, Section III provides the first study of soft paternalism to directly compare how third-party observers politically evaluate hard and soft paternalistic regulatory interventions. The results reported here suggest that choice of regulatory instrument – law or nudge – makes a significant difference in the political responses of third party observers. Individuals perform less well scrutinizing nudges than they do scrutinizing laws, even when both interventions are equally visible. Holding constant all dimensions of the situation other than the choice of regulatory instrument – including magnitude of cost resulting from the unsuccessful policy – participants consistently blamed regulators less for nudges that fail to achieve their desired policy goals than for laws that fail to achieve their policy goals.

Thus, the response of Sunstein and Thaler to critics appears inadequate. The accountability architecture designed to hold regulators responsible in the context of command and control regulation performs less well in the context of nudges. It produces less blame and is more permissive. Even in plain view, nudges are more difficult to monitor than laws.

After diagnosing this accountability problem, Section IV of the paper turns to identifying potential causes of the problem. Section IV generates data about the causes of the divergence in blame allocations. Here, the paper undertakes what might be described as two diagnostic tests that produce data that will help us to understand why individuals might perform less well when evaluating nudges. These diagnostics operationalize two theories from the literature on nudges. In particular, it tests (a) whether individuals fail to perceive or conceptualize the creation of choice architectures as state action at all and (b) whether individuals conceptualize nudges as less coercive than law, even when the material costs of the two are equivalent.

Section V uses the data generated in the previous Section to develop a reengineered model of accountability. Nudges are valuable regulatory tools. If the traditional accountability architecture is inadequate to hold nudging regulators accountable, we might reengineer the traditional architecture to accommodate this approach. Thus the paper concludes by considering how new institutional designs could help debias individual judgments about blameworthiness and make regulators more accountable for failed nudges. This, in turn, would improve how nudges perform in regulatory impact assessments and thereby increase the viability nudges as regulatory tools. 


<!---

A large literature addresses the ability of nudges to change behavior. The literature on how to hold regulators accountable for nudges is much smaller. To the best of my knowledge, 

This paper then breaks new ground by identifying a new type of behavioral failure -- accountabilty architecture or behavioral government failure  

Apply the principles of behavioral economics to accountability architectures 

GF
we've look at BGF
accountability architecture is a sub-species of BGF

--->

#Section II: Efficiency versus Accountability

<!---Nudging "is all the rage." [@Willis2013, p. 1157] "More and more policies are coming to the fore that in some way nudge citizens toward more positive or productive behavior, and numerous essays and articles propose deploying nudges in one context after another." [@Calo2014, p. 784] Executive Order 13,563, "a kind of mini-constitution for the regulatory state," includes provisions that recognize "the potential value of ... nudges." [@Sunstein2013, p. 1830]

EO 13,563 represents the ascendency of the idea of the "behavioral market failure" (BMF). [@Sunstein2014c, p. 20] BMFs offer a "supplement to the standard account of market failures" and enlarge "the class of justifications for government regulation." *Id.*  --->

<!---Nudges appear to be effective regulatory tools, in at least some situations. One way of understanding the debate is to ask whether the effectiveness of nudges is fundamentally at odds with accountability.--->

"All models of administration," argued then Professor Elena Kagan, "must address two core issues: how to make administration accountable to the public and how to make administration efficient or otherwise effective." [@Kagan2001b, p. 2331] The question of how to increase the efficiency and effectiveness of regulation involves a question of *mechanism choice* - which tool available to regulators best addresses the problem. [@Maskin2008] By contrast, the question of accountability involves a question of which "actors have the right to hold other actors to a set of standards, to judge whether they have fulfilled their responsibilities in light of these standards, and to impose sanctions if they determine that these responsibilities have not been met." [@Grant2005, p. 29] Historically, "these two goals [efficiency and accountability] often conflict with each other." [@Kagan2001b, p. 2331] 

Regulation seeks to solve problems created by market failures; in particular, problems of externalities, market power, and asymmetric information. [@Wiener2011, p. 310] Regulators try to solve these problems through regulatory tools such as taxes, liability rules, and mandates. [@Pildes2014, p. 1602] At the root of the conflict between effectiveness and accountability is the fact that effectiveness is often best promoted by delegating significant political or legal power to regulators. [@Stewart1975, pp. 1676-1679] Successful implementation of regulatory tools often  "requires delegations that provide significant discretion to agency officials." [@Kagan2001b, p. 2331] In turn, the provision of broad discretion creates the opportunity for "government failure." Significant discretion exposes the public to significant downside risk. Discretion "can ... impose its own problems, including compliance costs, inhibition of innovation, ancillary risks, and rent-seeking." [@Wiener2011, p. 310] Further, as Todd Zwyicki argues, "[b]ureaucrats are themselves susceptible to biases." [@Zwyicki2014, p. 32] Thus, government failure is the counterpart to market failure. As regulation is the solution to market failures, accountability is the solution to government failure. [@Wiener2009, p. 311]

To this standard template, behavioral economics adds the idea of the "behavioral market failure." [@Sunstein2014c, p. 20] These offer a "supplement to the standard account of market failures" and enlarge "the class of justifications for government regulation." *Id.*  Where neoclassical approaches to regulation identify the market's propensities to err, behavioral economics identifies "the human propensity to err." [@Sunstein2014c, p. 16] As in the case of traditional market failures, nudges typically require delegation and discretion, which, in turn raises the risk of government failure. Nudges, like more traditional types of regulation, must address the tension between efficiency and accountability.

The challenge, then, facing regulators is not merely to select the the most efficient and effective tool. Rather, the challenge is to select that tool which will minimize the sum of market failures and government failures. [@Cole2002, p. 5] Up to this point, proponents of soft paternalism have generally focused on establishing that nudges serve as an effective tool to combat traditional and behavioral market failures. Proponents have not, however, established that nudges minimize the sum of government failures. In particular, proponents of soft paternalism have not established that nudges minimize what is arguably the most crucial type of government failure: accountability failures. 

##Accountability Architectures

There are two main oversight frameworks designed to avoid accountability failures. Technocratic oversight involves tools like impact assessments, cost-benefit analysis, cost-effectiveness analysis, and risk-risk tradeoff analysis. [@Wiener2011] These tools seek to reduce bureaucratic bias and information asymmetries between agencies and regulatory oversight bodies. [@Livermore2014b, p. 616] For example, Sunstein argues that "rules that embody soft paternalism should be subject to public scrutiny in advance, often through notice-and-comment rulemaking." [@Sunstein2013, p. 1826] Under this method, agency officials would evaluate nudges in order to determine if they are justified. Democratic oversight, by contrast, aims to create accountability through the ballot box [@Wiener2011, p. 310]. Soft paternalists advocate a standard similar to Rawls' publicity condition, which holds that laws are publicly acknowledged and individuals are aware, or can become aware, of the law [@Hausman2010, p. 132].  

Proponents of soft paternalism consider both of these options as mechnanisms of regulatory accountability. Although the approaches differ in many ways, both approaches require individuals - be they voters or technocrats - to engage in retrospective evaluation of nudges. In other words, both of these accountability architectures depend on individuals accurately perceive the blameworthiness of regulators for failed nudges. Hence the importance of this study: if individuals are *misperceiving* blameworthiness for nudges, then a central input that drives their judgments about accountability will be biased. 

Both technocratic and democratic accountability architectures depend on individuals accurately perceiving the blameworthiness of regulators for failed nudges. These judgments factor into the ultimate decisions of technocrats and voters in different ways, however. 

Political scientists argue that voters tend to think about assessing the actions of officials in two ways. \footnote{These two models are not mutually exclusive; they might be combined in various ways.\cite{Fearon1999} Here we present the two pure types.} On one account, voters sanction officials for failed policies. On the other, voters select politicians based on a forward looking assessment of what they hope will be accomplished. More abstractly, the sanctions model is a pure moral hazard model, while the selection model is an adverse selection model. [@Mesquita.draft, p. 7]

On the sanctions model, elections serve as "a sanctioning device that induces elected officials to do what the voters want," since "[t]he anticipation of not being reelected in the future leads elected officials not to shirk their obligations to the voters in the present." [@Fearon1999, p. 56] Voters' actions are a function of "their evaluations of officeholders on their actual performance in office rather than on hypothetical promises they might make during a campaign." [@Ferejohn1986, p. 6] If we assume that voters treat elections thusly, the Executive will be incentivized to exercise what control it does have over agencies to enact popular policies. Applying this view of elections to the DA model, the Executive will be incentivized to enact a "regualtory vision" that "represents the majority will," [@Bressman2003, p. 491] or else face punishment.  

A more forward looking approach to election is the *selection* model. Whereas the sanctions model assumed that candidates vying for office are homogenous, and are only distinguished by their policy choices, the selection model assumes the opposite. Voters seek to install officials that match their own ``type.'' [***FILL IN***] ``[V]oters can use the policy choices of politicians to draw inferences about their underlying characteristics ...''\cite[p. 831]{Fox2011}

DA fits most naturally with the sanctions model, but it is not incompatible with the selection model. While election promises are cheap talk, actions reveal information about a candidate's true type. Thus, actions of the agency can reveal information about the type of the Executive (which, presumably, the executive knows, and is incentivized accordingly).


##The Crucial Role of Information in Both Architectures

Derivative premised on Ferejohn model

Importance of information to Ferejohn model

In fact, even market forms require info processing

OK, so we need accountability -- and for that, we need information

So now the critique is set up -- explain why Nudges don't provide the information


##Strategies for Maximizing Information while Sustaining Effectiveness 

###Approach 1 --- No Transparency

First, contra Kagan, one might deny the need to hold government accountable for nudges because nudges are not coercive. On this view, the primary goal of accountability is to constrain regulators from unjustifiably materially disadvantaging certain interests (for example, violating principles of cost-benefit analysis) or paternalistically interfering with free choice. \citep{Grant2005} Nudges, however, are often described as achieving regulatory goals without imposing material incentives. For example, Sunstein and Thaler sometimes argue that soft paternalist ``intervention[s] must not impose significant material incentives.'' \citep[p. 2][Sunstein.draft.2014b] Unlike \emph{hard} paternalism, which imposes incentives by regulatory interventions like taxation, \emph{soft} paternalism at most \emph{immaterially} imposes incentives. One might argue that the performance of a regulatory tool that does not coerce ought not to be taxed by accountability concerns. On this view, accountability (and thus transparency) is a price that a regulatory tool pays for coercing individuals. If a tool operates absent coercion, the need for accountability --- and consequently the need for transparency --- diminishes. However, as Robert Sugden argues, ``[r]ealistically, the application of libertarian paternalism will involve trade-offs between the welfare gains resulting from the reduction of errors in decision-making and the costs that result from restrictions on choice.'' \citep[p. 369]{Sugden2009b} Nudges in practice do ``significantly obstruct'' individual choice. \citep[3]{Sugden2009b} Nudges make non-preferred outcomes \emph{cognitively} more expensive.\footnote{Overriding a default setting, for example, takes time and cognitive energy. That's the very point of the default. Pointing out that some choice architecture might well justify the imposition of the most beneficial architecture -- but it does diminish the conclusion that all architectures impose costs.} The nature of the coercion might be different from hard paternalism, but soft paternalism nonetheless coerces individuals.

Alternatively, one might deny the need to hold government accountable for nudges because nudges are align with ``higher order'' (or ``authentic'') individual choices. On this view, one can allow that nudges coerce, but insist that this type of coercion --- unlike the coercion characteristic of hard paternalism --- does not impede individual autonomy. Just the opposite, in fact: nudges help individuals achieve autonomy. If nudges help individuals act on their higher order desires, then perhaps lack of accountability is less of a concern. Empirical results, however, do not appear to support this argument. In a study of the acceptability of covert versus overt nudges, Felsen et al. consider the argument that ``covertly influencing decision processes such that the resulting decision is aligned with higher-order desires may actually enhance autonomy ... .'' \citep[p. 5]{Felsen2013} The results of their study did not support this argument, however. ``[O]verall we found support for our hypothesis that overt, rather than covert, influences'' are more acceptable. [@Felsen2013, p. 5]

ADD ZWYICKI CITE TO SHOW CONCERN WITH THIS APPROACH

###Approach 2 -- Targeted Transparency

If the very need for accountability cannot be reject, then it seems likely that nudges will need to be transparent in some measure. The question becomes how to balance the accountability-enhancing effects of transparency with the possibility that some types of transparency might decrease the the effectiveness of some nudges. One strategy, proposed by Sunstein and Thaler, is to make nudges entirely transparent at the wholesale level, but limit their transparency at the retail level. The hope here is that targeted transparency will retain the performance gains of nudges while allowing \emph{enough} transparency to produce accountability.

Nudges seek to take advantage of biases individuals' decision-making processes --- such as loss aversion, over-confidence, status quo bias, framing, and the tendency toward inertia [@Welch2010, p. 125-26] --- to produce socially optimal outcomes. Thus nudges ``that affect unconscious processing'' are not promulgated directly to their addressee. \citep[p. 3]{Sunstein2014}; Rather, because the nudge exploits a decision-making bias, they are ``covert''. [@Sunstein2014, p. 3] Regulators deploying nudges influence behavior by altering the environment in which individuals make choices. However, if users experience an awareness of being nudged, then there is a risk that at least some users will ``override'' the nudge. Users might correct against the bias that the nudge is seeking to exploit.

Thus, under targeted transparency, information about nudges is freely and openly disseminated among the political class -- agency officials, courts, journalists, and academics --- and anyone interested enough to incur the costs of obtaining relevant analyses. Crucially, however, information about the nudge is not explicitly disclosed to individuals making decisions within a regulated choice environment.

``In its simplest form, the publicity principle bans governments from selecting
a policy that it would not be able or willing to defend publicly to its own citizens.'' [@Sunstein2008, p. 244]

###Approach 3 --- Full Transparency

Finally, institutional designers might question the assumption that the performance gains associated with nudges depend on lack of transparency to the user. Loewenstein et al. test whether ``full disclosure can potentially be achieved with little or no negative impact on the effectiveness of the intervention.'' [@Loewenstein2014, p. 2] The study compared the effectiveness of a medical default under conditions where some participants were explicitly informed of the intervention. Loewenstein et al. conclude that their ``findings suggest that the effectiveness of nudges may not depend on deceiving those who are being nudged,'' which would imply that ``policymakers can satisfy the strong form of the transparency advocated in the House of Lords report, with little diminution in the impact of interventions.'' [@Loewenstein2014, p. 13]


To this point, most of the attention paid to soft paternalism has focused on its efficiency and effectiveness. Much less attention has been paid to the unique accountability problems posed by soft paternalism. 

# References
