**Chapter 1**
A behavioral approach to contemporary electoral accountability


# Introduction 

Fundamentally Schumpeterian idea that competitive elections are vitally important to translating citizen preferences to public policy.

Most theories of democracy find a central role for electoral accountability. Indeed, EA is one of the central institutional designs of the modern period. But how does EA work? How do hundreds of millions of discrete individuals exert control over an elected representative?  

The traditional model of electoral accountability has three serious shortcomings, however. *First*, the traditional model treats elected representatives as the primary actors in government. In fact, the demise of the non-delegation doctrine, and the rise of intra-government delegation, has increased the number of actors involved in making policy. *Second*, the traditional model divides the world into "lawmaking," which is endogenous to politics, and "probabilistic background factors," which are exogenous to politics. In fact, this divide is not nearly so neat. The rise of new regulatory tools, like nudging, has deeply complicated the relationship between endogenous and exogenous factors. *Third*, the traditional model assumes that congresspeople can change course when voters demand it. But this assumption sits uncomfortably with decades of jurisprudence holding that legal change must be slow and gradual, lest it upset reasonable expectations. 

This basic model of electoral accountability has driven half a century of research. It has contributed much to our understanding of how elections produce a correspondence between public outcomes and private preferences. 

# Traditional EA

Since the pathbreaking work of V.O. Key, theories of electoral accountability have sought to explain how, if at all, citizens use competitive elections to officials accountable and to identify the predictable consequences of electoral accountability.^[K.J. Arrow and A. Downs wrote alongside Key, and together the three defined the modern "economic" approach to democratic theory.] The theory has two main results. First, it explains how private information held by citizens is translated to public policy (more specifically, translated to the production of public goods). Second, it explains the "self-reinforcing" nature of democracy. That is, it explains why those in power chose to hold elections *at all* (as opposed to merely using the power they already possess).

In order to see why these two functions are crucial, consider the problem facing a benevolent dictator seeking to provide a set of common goods to the public. The first problem the benevolent dictator would face is that of determining just what goods to provide. The dictator might have his own ideas about what goods to provide. If the dictator knows the optimal basket of public goods to provide, then the solution to the challenge is simple. In this case, the dictator can simply raise funds for the goods and provide them. [@Maskin2008]

It is unlikely, however, that even an benevolent dictator can maximize net social surplus^[Defined as gross social benefit minus the cost of providing the goods.] alone. This is because net social surplus is a product of citizens' preferences. Just as one would not ordinarily expect an auctioneer to know how much individuals will bid, likewise we tend to think that governments will not know, ex ante, citizens' preferences.

The first goal of a theory of EA, therefore, is to explain how to extract this information from citizens and translate it into policy. The solution is as indirect as it is elegant. It depends on an insight, first formalized as an economic theory by Key, about the way in which rational voters use elected officials' past performance as the basis for future decisions. [@Key1966] Key hypoethesized that voters will hold officials accountable for policies that do not accord with voters' preferences. This threat of electoral sanction incentivizes officials to act in the public interest. Elections are "a sanctioning device that induces elected officials to do what the voters want," since "[t]he anticipation of not being reelected in the future leads elected officials not to shirk their obligations to the voters in the present."[@Fearon1999, p. 56] The voter, then, is the "rational god of vengeance and reward." [@Key1964, p. 568.]

The more successful the voter in doling out vengeance and reward, the less "agency slack" in the system of representative democracy. Agency slack represents the difference between what voters want, and what elected officials do. The less slack in the system, the more the electoral system promotes the preferences of voters. Hence, "[t]he standard justification for electoral democracy is that competitive elections give leaders an incentive to provide public goods and more generally to align public policy with citizens' preferences." [@Fearon2011, p. 1661] 

Promoting the preferences of voters is important because, on the economic model of democracy, "[v]oters and citizens are the ultimate principals of the policymaking process." [@Weingast1984, p. 151] "[C]ongressmen are" merely "their agents." [@Weingast1984, p. 151] Voters delegate power to elected representatives. Delegation is an implicit or explicit contract that conditionally grants "authority from a principal to an agent that empowers the latter to act on behalf of the former." [@Abbott2015, p. 3] Although a "contract" is in place between principal and agent, the agent is constrained primarily (and perhaps *totally*) by the sanctioning and reward mechanism. Principals select agents with regard to their governance capacity, not their governance goals. [@Abbott2015, p. 5] Sanctioning and reward mechanisms are what determines how the agent acts.    

Across political, economic, and social life, principals have ways of reducing the "agency costs" that inevitably arise when power is delegated.  These methods seek to reduce the costs of shirking, information asymmetries, monitoring costs, and so forth. In the context of democracy, elections are the primary tool^[They are not, however, the only tool. Separation of powers also operates to reduce agency slack, by reducing the probability that factional interests will confound the general will.] for citizen-principals to reduce the agency costs of a representative democracy. 

If elections are efficacious, officeholders' decisions are driven by a comparison of the present value benefit of two alternative income streams: the benefits of impressing the voters and (increasing the probability of) remaining in office versus the benefits of shirking and (increasing the probability of) leaving office. [@Barro1973] Although performance depends jointly on the actions of the officeholder and exogenous factors outside of the officeholder's control, the electorate is able to observe "simple performance metrics," such as the state of the economy. [@Malhotra2013, p. 286] If, as Ronald Reagan asked, voters are "better off [today] than [they] were four years ago," then the officeholder is likely to be reelected. [@Malhotra2013, p. 286]

Traditional EA treats such outcomes as an indication that "elected officials [did] what the voters want." [@Fearon1999, p. 56] We can assume that agent-representatives true preferences differ from those of his constituents. [@Barro1973, p. 25] That is, because the agent-representatives did what the public wants, they diverged from what *they* wanted to do. Thus, if voters are happy, we can assume that elections are operating to incentivize agent-representatives: elections are obliging agent-representatives to act in certain ways, on pain of sanction. [@Fearon1999, p. 55] This conclusion, in turn, allows an observer to conclude that a contractual agency relationship exists.

But why should elected officials, once in office, continue to fund and hold elections?^[This prospect seems a bit far fetched, but we might be witnessing a related phenomenon today in the form of gerrymandering. Gerrymandering is, in a sense, a way of avoiding the practical realities of elections without actually cancelling them.] Social contract theorists, such as Locke, recognized that the threat of rebellion can be used as a last resort to keep elected officials in line. The problem with this solution is it assumes that the citizenry has access to good information about incumbent perfomrance. In fact, in increasingly complex and technocratic societies, evaluating official performance from without is very difficult. The closest incumbents can come to demonstrating to the public that they are acting in the public's interest is to hold elections. [@Fearon2011] Of course, gross malfeasance might be revealed in any particular case. Nixon's recorded phone calls, for example, offered strong proof of malfeasance. But as an *institutional* solution, we can't rely on evidence of this sort emerging. Holding elections, with easily understood and public rules, offers an instituitonal solution to the coordination problem of evaluating incumbent performance, and thus incentivizes incumbents to fund and hold future elections. 

The continued maintenance of agency relationship, as confirmed by the existence of elections, authorizes otherwise ordinary individuals to govern through coercive measures. To put it differently, if we could *not* identify a mechanism through which public preferences were reliably turned into policy, we could conclude that the purported agent-representatives are, in fact, not authorized to govern coercively.          

In order to know how to evaluate how well Traditional EA functions, both empirically and normatively, we should consider the *type* of theory that is on offer. That is, What is the theory trying to do?

FRAME WITH MORAL HAZARD OF GOVERNMENT FROM FEARON2011
PLUS ALSO MAYBE ADD THE STUFF ABOUT ECONOMIC VOTING BEING GOOD PROXY FOR PUBLIC GOODS - MAYBE AS FN

# What *is* a theory of electoral accountability? A brief overview of mechanism design 

Traditional EA is one of the most successful instances of an approach to social science called "mechanism design." [@Maskin2008] Mechanism design "can be thought of as the 'engineering' side of economic theory," as opposed to the purely explanatory side of economic theory. [@Maskin2008, p. 567] It is useful to compare mechanism design to the more well-known fields of game theory and decision theory. Where game theory "takes the rules of the game as given, and [] makes predictions about the behavior of strategic players," mechanism design "is about the optimal choice of the rules of the game." [@Borgers2015, p. 2] For designers, identifying the optimal choice of rules typically depends on predicting how individuals will behave in certain environments. Both mechanism design and game theory, therefore, rely on identifying equilibriums -- that is, joint strategic solutions where no one involved has an incentive to deviate from the strategy that they are playing.[@Maskin2008, p. 571, fn. 4]   

In order to determine an optimal set of rules in which individuals act in equilibrium, the designer must have a set of goals or values to guide the design process. With its roots in American democracy, Traditional EA is tightly aligned with the social contract theory of democratic legitimacy. Hence, it was of utmost importance to explain how certain individuals could come to possess the power to coerce the population.^[One might deviate from this normative view and nonetheless still find Traditional EA (or variant thereof) to be normatively valuable, if one's preferred normative explanation has a large role for accountability of the sort described thus far. For other types of accountability, see @Grant2005] The answer to this problem of authority, Traditional EA argues, is to design an institutional system that ensures that elected officials act in the general interests of the population by advancing regulation that responds to market failures. For the reasons discussed in the prior section, the existence of a system of accountability is the mechanism by which this is ensured. For most economists, the value to be achieved is some version of Pareto optimality. However, the values might just as well be cashed out in terms of utility or rights. [@Pattanaik1992]  Mechanism design aspires to be a method of general applicability.  

## The four quadrants of mechanism design 

Thus far we have treated mechanisms as institutions "designed" by scholars or policymakers. In fact, this is a simplification of a more complex reality. Some mechanisms are, in fact, designed from scratch by identifying a desired outcome and then seeking to create institutions that achieve that goal. For example, Eric Posner and E. Glen Weyl have been recently developing a voting procedure that, they argue, puts the appropriate value on strength of preference. This procedure, which they call Quadratic Voting, derives from already existing "weighted voting" procedures; the Posner and Weyl proposal, however, iterates on existing procedures by formalizing a system for individuals to buy votes. [@Weyl2014] Posner and Weyl acknolwedge the political infeasibility of such a system, an admission which highlights the extent to which it departs from convention. 

Alternatively, mechanism design my proceed by identifying real-world institutions and interpreting those institutions as a product of rational choices by their designers. [@Borgers2015] This type of mechanism design treats the institution under discussion *as though* it were created from scratch, and designed to achieve a stipulated set of values. Traditional EA is this latter type of mechanism design. It identifies a real-world institution (an electoral procedure) and interprets it as the product of a rational design intended to achieve legitimate political arrangements, assuming a social contract theory of political power. As we saw in the previous section, Traditional EA explains elections as institutions designed to transmit the preferences of discrete individuals to public policy. This outcome -- i.e., the existence of a principal-agent relationship -- is (taken to be) normatively valuable because it legitimates the rule of agent-representatives.^[Writers in the purely normative tradition have not always appreciated this relationship. Beitz, for example, argues that Downs' theory of spatial party competition is somehow covertly normative. In fact, Downs, and others in this tradition, are fully transparent about the normative underpinnings of their work. See [@Beitz1989, p. 182]]

Mechanism designs also vary along another axis: the degree to which they offer abstract or concerete solutions. [@Maskin2002] Abstract mechanisms seek to be robust against as many implementation details as possible. They seek high levels of fault tolerance. *Id.* Concrete approaches, by contrast, make more assumptions. Typically, abstract theories advance first, and then concrete theories follow in their wake. *Id.* 

These two axes produce the graph in Figure 1. The bottom right quadrant represents highly abstract, new ideas. The upper left quandrant, by contrast, represents highly concrete, existing institutions.   

These positions do not represent opposing approaches. In theory, a complete understanding of the phenomenon should allow for each point on the graph to be occupied by a slightly different account. In practice, our understanding progresses through a dialogue between different quadrants.^[For example, Maskin argues that "since so much has now been accomplished toward developing implementation theory at a general level, future efforts are likely to concentrate more on concrete applications of the theory, e.g., to contracts or to externalities. Another direction in which we expect the literature to develop is that of bounded rationality." [@Maskin2002, p. 282]] 

Where an account lies on the graph tends to be a product of how it treats three major factors. The first of these factors is how it defines the primary actors, or agents. Second, how does the account explain the alternative actions available to the agents?  Third, how does mechanism work? 

For Traditional EA, the agents are principal-voters and agent-representatives. Two types of actions are available to these agents: voting and law-making. The mechanism works by aligning voter preferences and policies at each election interval. If individual preferences shift, there should be a concomitant shift in policy.  

# Contemporary EA

*Contemporary* EA updates the traditional study of electoral accountability in two primary ways. Empirically, it reflects substantive changes in the institutional environments that surround the process of lawmaking. Normatively, contemporary EA takes a broader approach to legitimating the relationship between government and citizens. Recall, the empirical structure of the mechanism design is driven by background normative concerns. The growth of the administrative state necessitates a broader approach to accountability. Limiting accountability merely to elected representatives leaves a vast swath of political power unattended to.  

Traditional EA explains the normative significance of the agency relationship between representatives and citizens. But the relationship between citizens and the rest of government is not explained. Some Traditional EA theorists have sought to incorporate an account of the administrative state into Traditional EA. These accounts treat the bureaucracy as agents of elected representatives. These accounts, however, assume that bureaucracies operate like an assembly line.^[See also [@Christiano2005]] In fact, agencies wield discretion to such a degree that they are not appropriately characterized as agents of elected representatives. [@Stewart1975] 

We can put the point more forcefully. The breadth of policymaking that happens outside of Congress undercuts the claim that Traditional EA makes about legitimating power relationships. Traditional EA does not explain how voter preferences are transmitted to agencies that create policy. This deficiency undermines the purpose of the Traditional EA account. 

Contemporary EA seeks to reinvigorate the normative force of the electoral mechanism. Rather than abstracting away the administrative state, it confronts it directly, and incorporates its role in its theory of electoral accountability. FORMALIZING KAGAN'S PRESIDENTIAL ADMINISTRATION. 

## Empirical updates

Contemporary EA situates the study of electoral accountability in an environment that highlights important aspects of the contemporary political landscape. 

### The role of the administrative state in making policy

First, the process of policymaking has become more complex. In the Traditional EA account, the primary actors in the system are principal-voters and agent-representatives. By contrast, the administrative state is not a meaningful part of the story. A handful of pieces within the Traditional EA approach *have* sought to incorporate the administrative state; but those accounts stress that "it is not a bureaucratic imperative that drives agency decisionmaking but rather a congressional-electoral one." [@Weingast1984, p. 149] Agencies that fail to adhere to congressional discipline are sanctioned; "political discipline and motivation for regulatory policy choice works through Congress." [@Weingast1984, p. 149]

### The tools available to policymakers 

Second, policymakers -- be they representatives or agencies -- have new tools at their disposals. The Traditional EA account abstracts away the choice of tool. Only the consequences of policy matter, not the intentions of representative-agents or the means they use to achieve their policies. The types of actions taken by the representative-agents are not themsleves consequential; rather, it is simply assumed that preferences are translated into policy. [@Ashworth2014, p. 567] As a result, the traditional account ignores (a) the intentions behind the act and (b) the mode of action.  

### The limits to policy change 

Just as Traditional EA abstracts away the choice of tool to translate preference to policy, so too does it simply assume that a change in policy seamlessly translates to a change in regulation. Another way to put this is that Traditional EA treats policy change as costless. That is, it is assumed that, if individual preferences shift, there should be a concomitant shift in policy and in real-world regulation.  

Our best thinking about law, however, complicates this picture. Law, almost every legal philosopher and social scientist in the 20th century argues, is the kind of thing that must be stable. This is primarily due to the importance of maintaining reasonable expectations. Meanwhile, social scientists have pointed out the difference between "law on the books" and "law in action." 

## The normative problem created by these changes

Traditional EA abstracts away each of these issues. In theory, Traditional EA should be robust enough to handle each of these scenarios. These scenarios should raise mere "implementation details." However, once you remove the assumption that the administrative state is an agent of Congress, the logic of Traditional EA electoral accountability falls apart. Recall, the problem for citizens is to design a system such that incumbents are sufficiently incentivized to act in the public interest. This is a special version of the more general principal-agent problem. [@Manin1999, p. 41] Yet if those making a substantial fraction of policy are not, in fact, the citizens' agents, there is no mechanism of control. 

## A new brand of electoral accountability

It is one thing to provide new empirical evidence supporting the claim that the Traditional EA account is not, in fact, compatible with the contemporary political world. This dissertation goes beyond that. It offers a new model of electoral accountability that accounts for these three key changes in the contemporary political landscape. 

The first three empirical Chapters of the dissertation elucidate key new insights into the contemporary political process. The final Chapter of the dissertation then incorporates those insights into a revised conception of electoral accountability, which I refer to as Contemporary Electoral Accountability ("CEA").^[CEA does not directly compete with Traditional EA. CEA is, by design, more concrete than Traditional EA. If CEA is incompatible with Traditional EA, then it is incumbent upon advocates of Traditional EA to update the theory.]

### Derivative liability 

The "conventional wisdom" among public law scholars holds that regulatory policies created by administrative agencies "should be maximally responsive to the preferences of a majority of the electorate." [@Stephenson2008, p. 56] The difficulty is that the officials staffing agencies are appointed, not elected. Scholars seeking to legitimate the "headless fourth branch" of government through electoral accountability need a mechanism by which citizen preferences about regulatory policy can discipline agencies. According to the conventional wisdom, "the best way to assure bureaucratic responsiveness to majoritarian preferences is to make agency policy choices as responsive as possible to the preferences of the elected political leadership." [@Stephenson2008, p. 56]

The new mechanism presented in CEA is based on an approach to accountability first made prominent by now-Supreme Court Justice Elena Kagan. The central insight, as Justice articulated in *Chevron v. Natural Resources Defense Council, Inc.*, is that ``[w]hile agencies are not directly accountable to the people, the Chief Executive is ... .''\cite{467 U.S. 837, 865 (1984)} Agencies, then, might be held *derivately* accountable through the Executive branch. Agency policy choices that draw the ire of the electorate, on this view, can be expressed through punishment of the President, who is \emph{primarily} liable to voters. Indeed, a similar logic concludes that agencies can be held derivatively liable via the Legislative branch. Just how much discretion the possibility of derivative liability buys agencies --- whether one concludes, with the Supreme Court in *Chevron*, that it is therefore ''entirely appropriate for this political branch of the Government to ... make policy choices...'' or seeks to establish stricter limits on all agencies or some subset of them\cite{Stephenson2011} --- is a separate question. But the insight promises to offer an electoral mechanism through which agencies can be subjected to political discipline.

Using the empirical insights developed in Chapters 2-4, Chapter 5 provides a new theory of electoral accountability. This approach, I will argue, outperforms competing approaches to legitimating the administrative state. These approaches include, inter alia, the "fiduciary" approach.^[This discussion will overlap with discussions of the legitimacy of the administrative state. This is because both my question and the purely normative question are interested in the question of how the bureaucracy behaves in a democracy.]  

# What we know about voters

The approach taken here, like the Traditional account, assumes the worst about elected officials. This assumption is important because the mechanism does not depend on the quality of officials.^[Compare Caselli and Morelli, considering the possibility that voters elect low-quality candidates. [@Caselli2004]] But what about the competence of voters? V.O. Key famously declared the voter to be the "rational god of vengeance and reward."[@Key1964, p. 568] Generations of scholars have tested that claim. Most famously, perhaps, the "Michigan School" argued that voters lack both information and competence. [@Malhotra2013] We are, by now, painfully familiar with data showing that voters lack what appear to be certain forms of crucial information. As Arthur Lupia writes:

When it comes to political information, there are two groups of people. One group understands that they are almost completely ignorance of almost every detail of almost every law and policy under which they live. The other group is delusional about how much they know. There is no third group. [@Lupia2015, p. 3]

Some have sought to make a virtue of this ignorance. Fiorina argues that voters only need the most modest information about the economy to make electoral accountability work. [@Fiorina1982] Arthur Lupia argues that voters are rationally uninformed. It makes more sense, Lupia argues, for voters to simply take cues from party elites. [@Lupia1994]

Others take a more pessimistic view of the situation. Some argue many citizens - those ignorant of certain facts - have a moral obligation not to vote. Others go further. Democracy, Jason Brennan argues, is "the rule of the ignorant and the irrational, and it too often falls short." [@Brennan2016] Instead, we should be subject to the "rule of the knowledgeable." *Id.*

Fortunately, this dissertation is designed to avoid these questions. 

## A normative benchmark

Whatever nasty things you can say about voters' intelligence or beliefs, it is clear that they establish a normative benchmark.

Elections are at center of unrivaled normative hegemon. Kolodny2014 on democratic decision making

Whatever negative conclusions you might draw about voters ability to shape elections, it is clear that is has been *good enough* to be the lynchpin moment in an unrivaled institutional practice.

Voters perform *well enough* to ground the legitimacy of the practice. (Kutz- correspondence confirmed by electoral institutions- legitimacy. Legitimacy is product of practice and theory.)

## Accountability Architectures

If voters' performance in elections with traditional institutions is good enough to establish a normative benchmark, then going forward we should test capacity against that.

"Institutional design" is a popular field of public law. Designers identify problems associated with particular institutional arrangements and propose solutions. Sometimes those solutions are adopted. When they are, we cannot assume that individuals will perform as well at holding officials accountable as they did in the traditional arrangements.

We do *not* know how voters perform under conditions of COMPLEXITY and TOOLS. 

# A behavioral approach

The dissertation offers a *behavioral* approach to contemporary electoral accountability. This approach has two primary components.

Antecedents of the account in [@Anderson2007]

## Experimental

Experiments over theory

Using insights from economics, psychology and philosophy about the dynamics of group behavior and blame.  

### Self-interest through delegation 

Hamman

Delegate to powerless intermediary

Kutz

### Blameworthiness

Extensive literature 

Two ways to conceptualize blame. 

First, blameworthiness as necessary condition for electoral accountability

Second, blameworthiness as proxy for voting patterns - holding all else equal 

## Legal Realism 

Traditionally studies of EA depend on a rigid legal formalism. 

Traditional studies have little say to bat what happens afterwards.

This dissertation integrates into the study of EA a more contemporary view of law. I use the term "legal realism" not to denote the movement of the 1920s and 30s, ***. 

# Results

The results of this approach to electoral accountability are ***. 

## The bad news

In broadest terms, new accountability architectures appear to impede electoral accountability. 

Complexity and indirectness reduce the quality of individual judgments about blameworthiness.

## The good news

Debiasing and policy recommendations 

When change *does* occur due to electoral incentives, change is more possible than previously imagined. 

# Roadmap 
