**Chapter 1**
A behavioral approach to contemporary electoral accountability

# The puzzling place of electoral accountability

Imagine that you are at an auction. Fine art, farm equipment, or government-seized property: the items on the block don't matter much. After much yelling and hand waiving, the auction concludes. Then the auctioneer yells, "OK, the auction's over; now it's time to put the goods in the hands of those who value them the most!" 

How would attendees react? At best, attendees would be confused. After all, an auction is a process designed precisely to put goods in the hands of those who value them the most. 

Next, imagine that you are watching the final game of the NCAA basketball tournament. The buzzer sounds, and victorious team celebrates at halfcourt. Then the announcers yell, "OK, now it's time to figure out who the best team is!" Again, it would be hard to know how to respond. Single elimination tournaments are designed pricesely to determine who the best team is. 

Today, a logic very much like that found in the above two examples confuses our democratic process. Yet unlike the case of the auctioneer or basketball tournament we do not recognize the logic as odd. In fact, just the opposite is true. Across the political spectrum, we treat this logic as not only a legitimate feature of the democratic process, but a necessary one. 
An example from President Barack Obama's second term will illustrate the puzzling place of this logic at the heart of the democratic process.  

## Is electoral accountability a value? 

In June 2015, a full 18 months before the 2016 Presidential election, The New York *Times* wrote at length about the political problems facing President Obama. The bulk of these owed to the fact that he "never has to face voters again." Due to term limits, President Obama could not seek another term in office. This limitation resulted in an inability to "find[] new sources of political energy" in the absence of an upcoming election. Despite his democratic bona fides - President Obama won two elections - term limits created political headwinds. Without an ability to "face the voters" again, the democratic mandate that President Obama once possessed was percieved as diminished. 

Electoral accountability, according to this narrative, functions as a type of *politcal asset*. Political assets of this sort are helpful in the types of bare-knuckle political battles that constitutional theorists like Bruce Ackerman and Alexander Bickel refer to as "everyday politics." Unlike "constitutional politics,"^[See Gerald Gaus, Justificatory Liberalism, p. 232] which is, in some important yet hard to pin-down sense, the realm of *principle*, everyday politics is the realm of brute political muscle. The *Times* piece, for example, centers on President Obama's difficulty in passing the highly contentious Trans Pacific Partnership, a multi-lateral trade deal. The TPP debate wasn't about matters of high principle: the debate centered on the bare-knuckles issue of which groups won and which groups lost under the deal.^[Later, in the 2016 Democratic primaries, globalization and trade become larger issues. At the time, however, such issues were not front-and-center in Washington.] Absent an opportunity to stand before the public, President Obama lost a critical political asset. 

Yet the inability to face the voters affected President Obama in the realm of "constitutional politics," too. After Supreme Court Justice Antonin Scalia unexpectedly died in mid-2016, a debate immediately broke out over the issue of whether President Obama had the constitutional authority to appoint a new Justice. Those arguing that the President did not possess such authority made one point: that President Obama was a "lame duck." The argument was striking precisely because electoral accountability appeared to be transcending the realm of everyday politics: mainstream commentators were suggesting that President Obama lacked the constitutional authority to appoint a new Justice. The issue split along partisan lines initially. Yet today even some on the left seem to begrudgingly concede that President Obama's inability to face the voters placed a limitation on the President's scope of legitimate authority. (It didn't help those on the left when video surfaced of Vice President Joe Biden, a Democrat, appearing to have made a similar point.) Thus, the ability to face the voters appears to be more than just a political asset for bare-knuckle brawls, as as in the TPP trade case. Rather, the possibility of electoral accountability seems to be functioning as something like independent source of legal authority, one that increasingly appears to rival the traditional sources in the realm of "constitutional politics."

Treating electoral accountability as a political asset - and perhaps in the future even as something akin to a limitation on constitutional values - is so prominent that it borders on conventional wisdom. But this conventional wisdom suffers from the same illogic as the auction and basketball tournament examples above. When politicians, courts, or citizens call for democratic accountability, the situation is not unlike an auctioneer, after an auction has concluded, saying "OK, now it's time to put the goods in the hands of those who value them most!" Why? The process (the voting) produced a winner, holding certain authority, for a defined period of years. Critics who would deny President Obama the authority he already won are squarely analogous to the auctioneer who would deny the highest bidder his painting. 

To "face the voters" -- what is at the core of this powerful idea, which exerts such a large force on contemporary politics? The previous two examples suggest that it is a political value, and perhaps even an emerging source of quasi-legal authority. In this Introduction, I will argue that well-functioning electoral accountability is neither of these things, appearances to the contrary. Instead, I will argue that electoral accountability is a special case of what the economist Eric Maskin refers to as a "mechanism": an institution intentionally designed to bring about certain social goals. Electoral accountability refers to the possibility that voters will hold officials accountable for past trangressions or incentivize them to act in the public interest. Critics who treat electoral accountability as a political or constitutional asset are seeking to *transmute* a descriptive term into a normative value. Thus, electoral accountability is not a political value, nor a quasi-legal source of authority. In a way, that makes it much more mundane, and, when well-functioning, a lot less interesting. But electoral accountability is not functioning well right now. And this is why we are seeing it be transmuted in a political value and source of legal authority. This Introduction, then, diagnoses one of the consequences of a poorly functioning system of electoral accountability. The heart of the dissertation shows *why* it is poorly functioning and offers solutions to fix it. 

 ^[Let's eliminate three potential sources of question. First, whether an official transgressed a promise or acted in the public interest are normatively charged questions. But assuming agreement on those *background* normative matters, the question is in principle a positive one. Second, critics' arguments do not depend on the length of an officials' term or term limits. Those who would transmute electoral accountability into a normative term do *not* argue that four (or two, or six) years is too long. Finally, electoral accountability is treated as a normative idea even where an official does not face term limits.] 

## The mechanism is the value

Prior to investigating how electoral accountability factored into President Obama's second term in office, we left off with a question: How would listeners react to an auctioneer or announcer who seeemed to misunderstand the point of an auction or tournament. In both of these cases, the most natural response is to want to explain to the speaker how auctions, or basketball tournaments, work. Their remarks suggest that the speakers simply *don't understand* what just happened. The auction is a process designed to fetch the highest price for goods; playoffs are designed to pick out the best team. To suggest that those goals need effectuating through some *further* process is to misunderstand what just happened. 

It's possible, however, that the speakers *very well* understand what just happened. A playoff might be *designed* to find the best team, but in fact fail to accomplish its goal. In that case, it would make plenty of sense to suggest that the best team might not have been identified. A critique to this effect is often made of the NCAA tournament. The tournament is known as "March Madness" because of its single-elimination format. One slip up, and a team is out. Critics argue that, while the "madness" makes the tournament very entertaining, the tournament's single elimination format does reliably produce the best team. 

Thus, the auctioneer or announcer could be either terribly informed about the processor very well informed about it. How do we decide? Most of us would probably consider two aspects of auctions, or tournaments, or whatever process was under consideration. First, we would ask if there is some *external* standard by which we can judge the outcomes of the process. In the case of the NCAA tournament, there is: does the process produces the best team? We have factors that help us evaluate the quality of teams *other than* the outcome of the tournament. These criteria might include things like the quality of individual players, statistics, and probably the oldest external criteria in sports, the "eye test." To stretch John Rawls' terminology, the basketball tournament is an example of imperfect procedural justice. There is an independently good, just, or valuable outcome; and the procedure only imperfectly produces that outcome.

Dissatisfaction with existing procedures often arises when the assumptions underlying the procedure change. For example, in-person auctions came to look hopelessly imperfect in the internet age. The goal of auctions is to put goods in the hands of those who value them the most, and unnecessarily limiting the pool of potential buyers by geography appeared to be an unnecessary source of error. Today, most auctions of any significance occur with at least an online component.^[For a history of the auction, see Auction Problems: Going, Going, Gone, Leonard D. DuBoff, Cleveland State Law Review.] 

When such underlying fundamentals shift, the procedure is less able to achieve its purposes. Even revered, time-honored procedures can begin to look flawed in the face of changing conditions. The in-person auction was a staple of capitalist life. But if the procedure fails to achieve its aims, the other aspects of social life that depend on those aims being satisfied suffer. Typically, there is a period of suffering, where procedures have not been updated to reflect changed assumptions and as a result social goals are frustrated. In this period, what an observer of social life hears might not be a clarion call to change the procedure. Instead, one might hear the *aims* of the procedure, which are currently not being fulfilled, discussed. For example, those who see the NCAA Tournament as failing to produce the best team might create computer simulated tournaments, where each team plays each other team many times. Such unofficial, unsanctioned, and alternative procedures are ways to try to approximate the social goal that the official procedure is failing to realize.     

We are currently at such a moment with one of the most important procedures in our society, the democratic procedure.  Assumptions underlying the process have shifted, and the procedure is no longer producing the results it aims at. This is why refrences to "democratic accountability" proliferate. When politicians, courts, or citizens call for democratic accountability, the situation is not unlike an auctioneer, after an auction has concluded, saying "OK, now it's time to put the goods in the hands of those who value them most!"  

Of course, the democratic process is not as easily altered as an auction is. And so while some call for an overhaul of the democratic process, the sense of frustration with the process seeps out in other ways. We hear democratic accountability treated as a political value, or appraisive concept. Frequently, it functions in political discourse not as a description of the outcome of a process (the ballot box), but, rather, as a goal to be achieved. This is so common, it no longer seems odd. But in fact it is quite like the auctioneer suggesting that the goods didn't go to the highest bidder. 

We see democratic accountability acting as an appraisive value, and a legal tool. Why do we see these calls? 


# Introduction

All theories of democracy find a central role for electoral accountability. Elected officials must "face the voters." In so doing, the public judges politicians' performance; a verdict is rendered. But just what role does electoral accountability play in democratic societies? 

One approach to answering this question is to think about political power in the *absence* of electoral accountability. Term limits prevent incumbents from running for future terms, and thus allow incumbents to act without future electoral judgment. Colloquially -- and with more than a hint of derision -- refer these incumbents as "lame ducks." Consider a recent example. In June 2015, a full 18 months before the 2016 Presidential election, *The New York Times* wrote at length about the political problems facing President Barack Obama, owing directly to the fact that he "never has to face voters again." Underlying Obama's troubles at the time was a general inability to "finding new sources of political energy" in the absence of an upcoming election. Despite his democratic bona fides - Obama won two elections - term limits created political headwinds. Without an ability to face the others again, the democratic mandate that Obama once possessed was diminished. This example suggests that electoral accountability is a type of *political* value.

Political values of this sort are helpful in the types of bare-knuckle battles that constitutional theorists like Bruce Ackerman and Alexandar Bickel call "everyday politics." Unlike "constitutional politics,"^[See Gerald Gaus, Justificatory Liberalism, p. 232] which is, in some important sense, the realm of principle, everyday politics is the realm of brute strength. The *Times* piece, for example, was referring to Obama's difficulty in passing the highly contentious Trans Pacific Partnership, a multi-lateral trade deal. The TPP debate wasn't about matters of high principle: the debate centered on the comparatively simple issue of which groups won and which groups lost under the deal. Absent an opportunity to stand before the public, Obama appears to have lost a critical political tool.  

More recently, however, Obama's inability to face the voters has affected a quite different aspect of his job. After Supreme Court Justice Antonin Scalia unexpectedly died in mid-2016, a public debate immediately broke out over the issue of whether Obama had the *authority* to appoint a new Justice. Those making the argument cited one point: Obama is a lame duck. The argument was striking precisely because electoral accountability appeared to be transcending the realm of everyday politics: mainstream commentators were suggesting Obama lacked the *constitutional* authority to appoint a new Justice. This, Ackerman and Bickel would not predict. When Republicans first argued that Obama lacked the standing to appoint a replacement to the Court the issue split along partisan lines. Yet today even some on the left seem to begrudgingly concede that Obama's inability to face the voters is placing a limitation on the President's scope of legitimate authority. (It didn't help those on the left when video surfaced of Vice President Joe Biden appearing to have made a similar point.) So the ability to face the voters appears to be more than just a political value, as as in the TPP case. Rather, it seems to be functioning as something like independent source of legal authority, one that increasingly appears to rival the traditional sources. Indeed, it appears to be so strong as to now be an independent source of authority in the realm of "constitutional politics."

To "face the voters" -- what is at the core of this powerful idea, which exerts such a large force on contemporary politics? The previous two examples suggest that it is a political value, and perhaps even an emerging source of quasi-legal authority. In this Introduction, I will argue that well-functioning electoral accountability is neither of these things, appearances to the contrary. Instead, I will argue that electoral accountability is a special case of what the economist Eric Maskin refers to as a "mechanism": an institution intentionally designed to bring about certain social goals. Electoral accountability is not a political value, nor a quasi-legal source of authority. In a way, that makes it much more mundane, and, when well-functioning, a lot less interesting. But electoral accountability is not functioning well right now. And this is why we are seeing it be transmuted in a political value and source of legal authority. In this Introduction, I will offer a broad overview of the reasons why electoral accountability is failing, and how to fix it. 

# A Puzzle

The most general way to describe a mechanism is as a way of reliably producing outcomes in public, social settings. Mechanisms are valuable because they offer us as much assurance as is possible that the goals we want to be realized will, in fact, be realized. For example, the rules of basketball are designed to result in the best team having the most points at the end of a game. "Best" here isn't circular: If a quirk in the rules is tending to produce winners that aren't the best, the rule will be changed. This is how the shot clock was introduced. Weaker teams could hold on to the ball for large chunks of the game, resulting in skewed outcomes. Likewise, an auction is designed to put goods in the hands of those who value them the most. And faculty search committee is designed to produce the best hire. 

Maskin argues that electoral accountability is just a special version of this more general way of trying to control the future state of the world. Electoral institutions establish processes for selecting candidates for public office, in such a way as to incentivize them to act in the public interest. To achieve this result, electoral institutions lead to a cascade of mutually-reinforcing incentives. These institutions (a) incentivize voters to retrospectively evaluate officials' performances such that (b) victorious candidates will tend to act in the public interest. This cascade is complex, but it is not unique to electoral mechanisms. Eliminating the shot clock in basketball led to changes in game plans, which lead to changes in the selection of players, which resulted in further changes to game plans. The ontology of a mechanism, then, is part institution, and part what Robert Nozick refers to as an "invisible hand" phenomenon. More succinctly, electoral accountability is a set of institutions, and the incentives that predictably flow from it. The promise of mechanism designers is that, if the institutions are created correctly, officials will be accountable to the public. And this accountability will occur as a matter of course: *mechanically*.

Something about this should be puzzling. If electoral accountability works as advertised, then we shouldn't need to make reference to it as a political value. "Mere values" - that is, values without institutional mechanisms to realize them - typically work only when explicitly or implicitly *appealed to*. Values must be *addressed*, precisely because there is no institutional mechanism to realize them. But we have mechanisms to realize electoral accountability. After an auction, no one says "OK, now it's time to put the goods in the hands of those who value them the most!" The auction takes care of that. In basketball, after a game, no one says "OK, now it's time to decide who the best team is." The game takes care of that. If we *do* find ourselves questioning whether the best team won after a game is over, it just means that the mechanism needs revising, as in the case of the shot clock introduction.  

Likewise, if electoral accountability works as advertised, why should we need to treat it as a quasi-legal concept, as Republicans seeking to stop the appointment of a new Justice did? Sources of legal authority, like political values, must be appealed to. Law requires a process of "naming, blaming, and claiming." If electoral accountability worked as advertised, we would not need to appeal to it as a source of quasi-legal authority. Indeed, it would be redundant to do so. 

Both treating electoral accountability as a political value or as a quasi-legal value are ways to trying to give force to the moral value of one person-one vote. In the absence of a well-functioning *mechanism* for achieving this goal, we reach for politics and law. We see electoral accountability transmuting to, alternatively, a politcal value (TPP) and quasi-constitutional norm (judicial appointments) - as opposed to a mechanism that we can rely on - because it is not functioning as intended. 

Our model of electoral accountability is not functioning as intended. Our current electoral mechanisms are premised on what I will call the "traditional" model of accountability. This model has three serious shortcomings. 

The traditional model treats elected representatives as the primary actors in government. In fact, the demise of the non-delegation doctrine, and the rise of intra-government delegation, has increased the number of actors involved in making policy beyond the legislature. The first flaw is about *who* gets to exercise political power. The second is about *how* that power is exercised. The traditional model divides the world into coercive lawmaking, which is characterized as endogenous to politics, and "probabilistic background factors," which are exogenous to politics. In fact, this divide is not nearly so neat. The rise of new regulatory tools, like nudging, has deeply complicated the relationship between endogenous and exogenous factors. If the first flaw is about who exercises power, and the second is about how power is exercised, the third flaw is about *when* power can be exercised. The traditional model assumes that congresspeople can change course when voters demand it. But this assumption sits uncomfortably with decades of jurisprudence holding that legal change must be slow and gradual, lest it upset reasonable expectations. 

The traditional model of electoral accountability has driven half a century of research. It has contributed much to our understanding of how elections produce a correspondence between public outcomes and private preferences. But it has failed to keep up with the development and growth of major political institutions and practices. This failure has led to the groping for new ways of realizing the moral value of one person-one vote. These ad hoc approaches - treating electoral accountability as a political or quasi-legal value - are insufficient. One person-one vote is so significant that it should be mechanized. One person-one vote should be assured. In order to chart a course back to a world where electoral accountability is assured, we need a broader picture of the traditional model that has failed. 

# Traditional EA

Since the pathbreaking work of V.O. Key, theories of electoral accountability have sought to explain how, if at all, citizens use competitive elections to officials accountable and to identify the predictable consequences of electoral accountability.^[K.J. Arrow and A. Downs wrote alongside Key, and together the three defined the modern "economic" approach to democratic theory.] The theory has two main results. First, it explains how private information held by citizens is translated to public policy (more specifically, translated to the production of public goods). Second, it explains the "self-reinforcing" nature of democracy. That is, it explains why those in power chose to hold elections *at all* (as opposed to merely using the power they already possess).

In order to see why these two functions are crucial, consider the problem facing a benevolent dictator seeking to provide a set of common goods to the public. The first problem the benevolent dictator would face is that of determining just what goods to provide. The dictator might have his own ideas about what goods to provide. If the dictator knows the optimal basket of public goods to provide, then the solution to the challenge is simple. In this case, the dictator can simply raise funds for the goods and provide them. [@Maskin2008]

It is unlikely, however, that even an benevolent dictator can maximize net social surplus^[Defined as gross social benefit minus the cost of providing the goods.] alone. This is because net social surplus is a product of citizens' preferences. Just as one would not ordinarily expect an auctioneer to know how much individuals will bid, likewise we tend to think that governments will not know, ex ante, citizens' preferences. This theoretical point is often borne out most acutely as political parties seek to select candidates, define their platforms, in the event of an electoral defeat, redefine themselves.^[Consider the post mortems after Kerry lost to Bush in 2004. http://www.washingtonpost.com/wp-dyn/articles/A50815-2004Nov15.html] [@Bendor2011, p. 52]

The first goal of a theory of EA, therefore, is to explain how to extract this information from citizens and translate it into policy. The solution is as indirect as it is elegant. It depends on an insight, first formalized as an economic theory by Key, about the way in which rational voters use elected officials' past performance as the basis for future decisions. [@Key1966] Key hypoethesized that voters will hold officials accountable for policies that do not accord with voters' preferences. This threat of electoral sanction incentivizes officials to act in the public interest. Elections are "a sanctioning device that induces elected officials to do what the voters want," since "[t]he anticipation of not being reelected in the future leads elected officials not to shirk their obligations to the voters in the present."[@Fearon1999, p. 56] The voter, then, is the "rational god of vengeance and reward." [@Key1964, p. 568.]

The more successful the voter in doling out vengeance and reward, the less "agency slack" in the system of representative democracy. Agency slack represents the difference between what voters want, and what elected officials do. The less slack in the system, the more the electoral system promotes the preferences of voters. Hence, "[t]he standard justification for electoral democracy is that competitive elections give leaders an incentive to provide public goods and more generally to align public policy with citizens' preferences." [@Fearon2011, p. 1661] 

Promoting the preferences of voters is important because, on the economic model of democracy, "[v]oters and citizens are the ultimate principals of the policymaking process." [@Weingast1984, p. 151] "[C]ongressmen are" merely "their agents." [@Weingast1984, p. 151] Voters delegate power to elected representatives. Delegation is an implicit or explicit contract that conditionally grants "authority from a principal to an agent that empowers the latter to act on behalf of the former." [@Abbott2015, p. 3] Although a "contract" is in place between principal and agent, the agent is constrained primarily (and perhaps *totally*) by the sanctioning and reward mechanism. Principals select agents with regard to their governance capacity, not their governance goals. [@Abbott2015, p. 5] Sanctioning and reward mechanisms are what determines how the agent acts.    

Across political, economic, and social life, principals have ways of reducing the "agency costs" that inevitably arise when power is delegated.  These methods seek to reduce the costs of shirking, information asymmetries, monitoring costs, and so forth. In the context of democracy, elections are the primary tool^[They are not, however, the only tool. Separation of powers also operates to reduce agency slack, by reducing the probability that factional interests will confound the general will.] for citizen-principals to reduce the agency costs of a representative democracy. 

If elections are efficacious, officeholders' decisions are driven by a comparison of the present value benefit of two alternative income streams: the benefits of impressing the voters and (increasing the probability of) remaining in office versus the benefits of shirking and (increasing the probability of) leaving office. [@Barro1973] Although performance depends jointly on the actions of the officeholder and exogenous factors outside of the officeholder's control, the electorate is able to observe "simple performance metrics," such as the state of the economy. [@Malhotra2013, p. 286] If, as Ronald Reagan asked, voters are "better off [today] than [they] were four years ago," then the officeholder is likely to be reelected. [@Malhotra2013, p. 286]

Traditional EA treats such outcomes as an indication that "elected officials [did] what the voters want." [@Fearon1999, p. 56] We can assume that agent-representatives true preferences differ from those of his constituents. [@Barro1973, p. 25] That is, because the agent-representatives did what the public wants, they diverged from what *they* wanted to do. Thus, if voters are happy, we can assume that elections are operating to incentivize agent-representatives: elections are obliging agent-representatives to act in certain ways, on pain of sanction. [@Fearon1999, p. 55] This conclusion, in turn, allows an observer to conclude that a contractual agency relationship exists.

But why should elected officials, once in office, continue to fund and hold elections?^[This prospect seems a bit far fetched, but we might be witnessing a related phenomenon today in the form of gerrymandering. Gerrymandering is, in a sense, a way of avoiding the practical realities of elections without actually cancelling them.] Social contract theorists, such as Locke, recognized that the threat of rebellion can be used as a last resort to keep elected officials in line. The problem with this solution is it assumes that the citizenry has access to good information about incumbent perfomrance. In fact, in increasingly complex and technocratic societies, evaluating official performance from without is very difficult. The closest incumbents can come to demonstrating to the public that they are acting in the public's interest is to hold elections. [@Fearon2011] Of course, gross malfeasance might be revealed in any particular case. Nixon's recorded phone calls, for example, offered strong proof of malfeasance. But as an *institutional* solution, we can't rely on evidence of this sort emerging. Holding elections, with easily understood and public rules, offers an instituitonal solution to the coordination problem of evaluating incumbent performance, and thus incentivizes incumbents to fund and hold future elections. 

The continued maintenance of agency relationship, as confirmed by the existence of elections, authorizes otherwise ordinary individuals to govern through coercive measures. To put it differently, if we could *not* identify a mechanism through which public preferences were reliably turned into policy, we could conclude that the purported agent-representatives are, in fact, not authorized to govern coercively.          

In order to know how to evaluate how well Traditional EA functions, both empirically and normatively, we should consider the *type* of theory that is on offer. That is, What is the theory trying to do?

FRAME WITH MORAL HAZARD OF GOVERNMENT FROM FEARON2011
PLUS ALSO MAYBE ADD THE STUFF ABOUT ECONOMIC VOTING BEING GOOD PROXY FOR PUBLIC GOODS - MAYBE AS FN

# What *is* a theory of electoral accountability? A brief overview of mechanism design 

Traditional EA is one of the most successful instances of an approach to social science called "mechanism design." [@Maskin2008] Mechanism design "can be thought of as the 'engineering' side of economic theory," as opposed to the purely explanatory side of economic theory. [@Maskin2008, p. 567] It is useful to compare mechanism design to the more well-known fields of game theory and decision theory. Where game theory "takes the rules of the game as given, and [] makes predictions about the behavior of strategic players," mechanism design "is about the optimal choice of the rules of the game." [@Borgers2015, p. 2] For designers, identifying the optimal choice of rules typically depends on predicting how individuals will behave in certain environments. Both mechanism design and game theory, therefore, rely on identifying equilibriums -- that is, joint strategic solutions where no one involved has an incentive to deviate from the strategy that they are playing.[@Maskin2008, p. 571, fn. 4]   

In order to determine an optimal set of rules in which individuals act in equilibrium, the designer must have a set of goals or values to guide the design process. With its roots in American democracy, Traditional EA is tightly aligned with the social contract theory of democratic legitimacy. Hence, it was of utmost importance to explain how certain individuals could come to possess the power to coerce the population.^[One might deviate from this normative view and nonetheless still find Traditional EA (or variant thereof) to be normatively valuable, if one's preferred normative explanation has a large role for accountability of the sort described thus far. For other types of accountability, see @Grant2005] The answer to this problem of authority, Traditional EA argues, is to design an institutional system that ensures that elected officials act in the general interests of the population by advancing regulation that responds to market failures. For the reasons discussed in the prior section, the existence of a system of accountability is the mechanism by which this is ensured. For most economists, the value to be achieved is some version of Pareto optimality. However, the values might just as well be cashed out in terms of utility or rights. [@Pattanaik1992]  Mechanism design aspires to be a method of general applicability.  

## The four quadrants of mechanism design 

Thus far we have treated mechanisms as institutions "designed" by scholars or policymakers. In fact, this is a simplification of a more complex reality. Some mechanisms are, in fact, designed from scratch by identifying a desired outcome and then seeking to create institutions that achieve that goal. For example, Eric Posner and E. Glen Weyl have been recently developing a voting procedure that, they argue, puts the appropriate value on strength of preference. This procedure, which they call Quadratic Voting, derives from already existing "weighted voting" procedures; the Posner and Weyl proposal, however, iterates on existing procedures by formalizing a system for individuals to buy votes. [@Weyl2014] Posner and Weyl acknolwedge the political infeasibility of such a system, an admission which highlights the extent to which it departs from convention. 

Alternatively, mechanism design my proceed by identifying real-world institutions and interpreting those institutions as a product of rational choices by their designers. [@Borgers2015] This type of mechanism design treats the institution under discussion *as though* it were created from scratch, and designed to achieve a stipulated set of values. Traditional EA is this latter type of mechanism design. It identifies a real-world institution (an electoral procedure) and interprets it as the product of a rational design intended to achieve legitimate political arrangements, assuming a social contract theory of political power. As we saw in the previous section, Traditional EA explains elections as institutions designed to transmit the preferences of discrete individuals to public policy. This outcome -- i.e., the existence of a principal-agent relationship -- is (taken to be) normatively valuable because it legitimates the rule of agent-representatives.^[Writers in the purely normative tradition have not always appreciated this relationship. Beitz, for example, argues that Downs' theory of spatial party competition is somehow covertly normative. In fact, Downs, and others in this tradition, are fully transparent about the normative underpinnings of their work. See [@Beitz1989, p. 182]]

Mechanism designs also vary along another axis: the degree to which they offer abstract or concerete solutions. [@Maskin2002] Abstract mechanisms seek to be robust against as many implementation details as possible. They seek high levels of fault tolerance. *Id.* Concrete approaches, by contrast, make more assumptions. Typically, abstract theories advance first, and then concrete theories follow in their wake. *Id.* 

These two axes produce the graph in Figure 1. The bottom right quadrant represents highly abstract, new ideas. The upper left quandrant, by contrast, represents highly concrete, existing institutions.   

These positions do not represent opposing approaches. In theory, a complete understanding of the phenomenon should allow for each point on the graph to be occupied by a slightly different account. In practice, our understanding progresses through a dialogue between different quadrants.^[For example, Maskin argues that "since so much has now been accomplished toward developing implementation theory at a general level, future efforts are likely to concentrate more on concrete applications of the theory, e.g., to contracts or to externalities. Another direction in which we expect the literature to develop is that of bounded rationality." [@Maskin2002, p. 282]] 

Where an account lies on the graph tends to be a product of how it treats three major factors. The first of these factors is how it defines the primary actors, or agents. Second, how does the account explain the alternative actions available to the agents?  Third, how does mechanism work? 

For Traditional EA, the agents are principal-voters and agent-representatives. Two types of actions are available to these agents: voting and law-making. The mechanism works by aligning voter preferences and policies at each election interval. If individual preferences shift, there should be a concomitant shift in policy.  

# Contemporary EA

*Contemporary* EA updates the traditional study of electoral accountability in two primary ways. Empirically, it reflects substantive changes in the institutional environments that surround the process of lawmaking. Normatively, contemporary EA takes a broader approach to legitimating the relationship between government and citizens. Recall, the empirical structure of the mechanism design is driven by background normative concerns. The growth of the administrative state necessitates a broader approach to accountability. Limiting accountability merely to elected representatives leaves a vast swath of political power unattended to.  

Traditional EA explains the normative significance of the agency relationship between representatives and citizens. But the relationship between citizens and the rest of government is not explained. Some Traditional EA theorists have sought to incorporate an account of the administrative state into Traditional EA. These accounts treat the bureaucracy as agents of elected representatives. These accounts, however, assume that bureaucracies operate like an assembly line.^[See also [@Christiano2005]] In fact, agencies wield discretion to such a degree that they are not appropriately characterized as agents of elected representatives. [@Stewart1975] 

We can put the point more forcefully. The breadth of policymaking that happens outside of Congress undercuts the claim that Traditional EA makes about legitimating power relationships. Traditional EA does not explain how voter preferences are transmitted to agencies that create policy. This deficiency undermines the purpose of the Traditional EA account. 

Contemporary EA seeks to reinvigorate the normative force of the electoral mechanism. Rather than abstracting away the administrative state, it confronts it directly, and incorporates its role in its theory of electoral accountability. FORMALIZING KAGAN'S PRESIDENTIAL ADMINISTRATION. 

## Empirical updates

Contemporary EA situates the study of electoral accountability in an environment that highlights important aspects of the contemporary political landscape. 

### The role of the administrative state in making policy

First, the process of policymaking has become more complex. In the Traditional EA account, the primary actors in the system are principal-voters and agent-representatives. By contrast, the administrative state is not a meaningful part of the story. A handful of pieces within the Traditional EA approach *have* sought to incorporate the administrative state; but those accounts stress that "it is not a bureaucratic imperative that drives agency decisionmaking but rather a congressional-electoral one." [@Weingast1984, p. 149] Agencies that fail to adhere to congressional discipline are sanctioned; "political discipline and motivation for regulatory policy choice works through Congress." [@Weingast1984, p. 149]

### The tools available to policymakers 

Second, policymakers -- be they representatives or agencies -- have new tools at their disposals. The Traditional EA account abstracts away the choice of tool. Only the consequences of policy matter, not the intentions of representative-agents or the means they use to achieve their policies. The types of actions taken by the representative-agents are not themsleves consequential; rather, it is simply assumed that preferences are translated into policy. [@Ashworth2014, p. 567] As a result, the traditional account ignores (a) the intentions behind the act and (b) the mode of action.  

### The limits to policy change 

Just as Traditional EA abstracts away the choice of tool to translate preference to policy, so too does it simply assume that a change in policy seamlessly translates to a change in regulation. Another way to put this is that Traditional EA treats policy change as costless. That is, it is assumed that, if individual preferences shift, there should be a concomitant shift in policy and in real-world regulation.  

Our best thinking about law, however, complicates this picture. Law, almost every legal philosopher and social scientist in the 20th century argues, is the kind of thing that must be stable. This is primarily due to the importance of maintaining reasonable expectations. Meanwhile, social scientists have pointed out the difference between "law on the books" and "law in action." 

## The normative problem created by these changes

Traditional EA abstracts away each of these issues. In theory, Traditional EA should be robust enough to handle each of these scenarios. These scenarios should raise mere "implementation details." However, once you remove the assumption that the administrative state is an agent of Congress, the logic of Traditional EA electoral accountability falls apart. Recall, the problem for citizens is to design a system such that incumbents are sufficiently incentivized to act in the public interest. This is a special version of the more general principal-agent problem. [@Manin1999, p. 41] Yet if those making a substantial fraction of policy are not, in fact, the citizens' agents, there is no mechanism of control. 

## A new brand of electoral accountability

It is one thing to provide new empirical evidence supporting the claim that the Traditional EA account is not, in fact, compatible with the contemporary political world. This dissertation goes beyond that. It offers a new model of electoral accountability that accounts for these three key changes in the contemporary political landscape. 

The first three empirical Chapters of the dissertation elucidate key new insights into the contemporary political process. The final Chapter of the dissertation then incorporates those insights into a revised conception of electoral accountability, which I refer to as Contemporary Electoral Accountability ("CEA").^[CEA does not directly compete with Traditional EA. CEA is, by design, more concrete than Traditional EA. If CEA is incompatible with Traditional EA, then it is incumbent upon advocates of Traditional EA to update the theory.]

### Derivative liability 

The "conventional wisdom" among public law scholars holds that regulatory policies created by administrative agencies "should be maximally responsive to the preferences of a majority of the electorate." [@Stephenson2008, p. 56] The difficulty is that the officials staffing agencies are appointed, not elected. Scholars seeking to legitimate the "headless fourth branch" of government through electoral accountability need a mechanism by which citizen preferences about regulatory policy can discipline agencies. According to the conventional wisdom, "the best way to assure bureaucratic responsiveness to majoritarian preferences is to make agency policy choices as responsive as possible to the preferences of the elected political leadership." [@Stephenson2008, p. 56]

The new mechanism presented in CEA is based on an approach to accountability first made prominent by now-Supreme Court Justice Elena Kagan. The central insight, as Justice articulated in *Chevron v. Natural Resources Defense Council, Inc.*, is that ``[w]hile agencies are not directly accountable to the people, the Chief Executive is ... .''\cite{467 U.S. 837, 865 (1984)} Agencies, then, might be held *derivately* accountable through the Executive branch. Agency policy choices that draw the ire of the electorate, on this view, can be expressed through punishment of the President, who is \emph{primarily} liable to voters. Indeed, a similar logic concludes that agencies can be held derivatively liable via the Legislative branch. Just how much discretion the possibility of derivative liability buys agencies --- whether one concludes, with the Supreme Court in *Chevron*, that it is therefore ''entirely appropriate for this political branch of the Government to ... make policy choices...'' or seeks to establish stricter limits on all agencies or some subset of them\cite{Stephenson2011} --- is a separate question. But the insight promises to offer an electoral mechanism through which agencies can be subjected to political discipline.

Using the empirical insights developed in Chapters 2-4, Chapter 5 provides a new theory of electoral accountability. This approach, I will argue, outperforms competing approaches to legitimating the administrative state. These approaches include, inter alia, the "fiduciary" approach.^[This discussion will overlap with discussions of the legitimacy of the administrative state. This is because both my question and the purely normative question are interested in the question of how the bureaucracy behaves in a democracy.]  

# What we know about voters

The approach taken here, like the Traditional account, assumes the worst about elected officials. This assumption is important because the mechanism does not depend on the quality of officials.^[Compare Caselli and Morelli, considering the possibility that voters elect low-quality candidates. [@Caselli2004]] But what about the competence of voters? V.O. Key famously declared the voter to be the "rational god of vengeance and reward."[@Key1964, p. 568] Generations of scholars have tested that claim. Most famously, perhaps, the "Michigan School" argued that voters lack both information and competence. [@Malhotra2013] We are, by now, painfully familiar with data showing that voters lack what appear to be certain forms of crucial information. "Two of the most robust findings about American voters," Bendor et al. summarize, "are that few of them have coherent, detailed ideologies and few know much about politics." [@Bendor2011, p. 109]  As Arthur Lupia writes:

When it comes to political information, there are two groups of people. One group understands that they are almost completely ignorance of almost every detail of almost every law and policy under which they live. The other group is delusional about how much they know. There is no third group. [@Lupia2015, p. 3]

Some have sought to make a virtue of this ignorance. Fiorina argues that voters only need the most modest information about the economy to make electoral accountability work. [@Fiorina1982] Arthur Lupia argues that voters are rationally uninformed. It makes more sense, Lupia argues, for voters to simply take cues from party elites. [@Lupia1994]

Others take a more pessimistic view of the situation. Some argue many citizens - those ignorant of certain facts - have a moral obligation not to vote. Others, citing "the depth of ignorance demonstrated by modern mass publics," go further. [@Bendor2011, p. 109] Democracy, Jason Brennan argues, is "the rule of the ignorant and the irrational, and it too often falls short." [@Brennan2016] Instead, we should be subject to the "rule of the knowledgeable." *Id.*

These debates have persisted for a long time, and quite frankly it's hard to see much progress being made. Wading into debates about voter competence is unlikely to produce new insights. Is it possible to advance a theory of electoral accountability while avoiding these debates? 

## A normative benchmark

This dissertation is designed to avoid intractable questions about voter competence. Whatever one might conclude about voters' beliefs, intelligence or capacity for reasoned deliberation, it is clear that voters' actions establish a normative benchmark. Elections are at center of unrivaled normative hegemon: the practice of democracy. While conceptions of democracy are many and contested, a system of free, fair, and open decisionmaking is at the heart of all of them. [@Beitz1989] Whatever negative conclusions you might draw about voters ability to shape elections, it is clear that is has been *good enough* to be the lynchpin moment in an unrivaled institutional practice. Whatever theory best explains why elections are good - whether they respect citizens qua equals or tend to produce the best outcomes - it is clear that voters perform *well enough* to ground the legitimacy of the practice.^[Under any reasonable standard of justification. [@Waldron1993]]

The aspects of this dissertation that relate to democratic decisionmaking do not seek to improve on current practices. Rather, this dissertation seeks to compare the efficacy of new practices with traditional practices. If voters' performance in elections with traditional institutions is good enough to establish a normative benchmark, then we should gauge the efficacy of new institutional arrangements against those performance under those institutional arrangements.

For the most part, mechanism designers have simply assumed that voters will perform as well under new institutional arrangements as they did under the previous arrangements. For example, advocates of the "Derivative Accountability" model of administrative accountability, discussed above, simply assume that voters' retrospective evaluations of *agency* action will be as competent as voters' retrospective evalutations of *legislative* action. As Chapters Two and Three reveal, these assumptions are unjustified.  

Mechanism design typically operates by identifying one problem, and identifying a fix for it. But, often, the solution can generate a *new* problem. By and large, mechanism designers have not tended to investigate these new problems that arise from their fixes. This dissertation does investigate these problems, and, what's more, it offers solutions to fix them. Of course, these solutions might *themselves* cause fresh problems. In this sense, the ideas presented here represent a part of an ongoing conversation about how to best accomplish democratic accountability, not a perfect solution.   

Predicting how individuals will react under new institutional conditions requires a research design that isolates the key differences between the two designs. In order to do so, this dissertation takes a *behavioral* approach. 

# A behavioral approach

Most of the prior work contributing to the Traditional EA approach proceeds on the rational choice approach. By contrast, this dissertation offers a *behavioral* approach to contemporary electoral accountability. A behavioral approach draws on the methodology and substantive insights developed by experimental economics and cognitive psychology. Although frequently touted as a competitor to rational choice approaches, [@Ostrom2000] behavioral approaches are better described as working in tandem with rational choice approaches. At their core, behavioral approaches *test* rational choice models by subjecting its assumptions to empirical scrutiny, often in the form of randomized control trials or quasi-experiments. Some behavioral approaches do more: they compare the concepts used by RC approaches with what are often thicker, richer concepts derived from philosophy or other humanities. If these concepts perform better than the RC concepts, then, ideally, they will be incorporated in suitably modified models.^[Behavioral studies tend to proceed data point by data point, from the bottom-up. Unlike RC theory, which is a top-down exercise, many behavioral studies are required in order to begin to build new theory. See, e.g., Dan Ariely's Predictably Irrational: The Hidden Forces that Shape Our Decisions.]

This pattern - integrating behavioral insights into RC models - is widespread across the social sciences. Yet it is peculiarly absent in the electoral accountability literature. To be sure, some RC scholars have sought to incorporate behavioral insights. Most notably, Bendor et al. authored *A Behavioral Theory of Elections* in 2011. Arguing that "a change is overdue," the book length work sought to incorporate insights around issues of bounded rationality to the study of electoral accountability. The key contribution of Bendor et al. was to show, as a formal matter, why voting is not irrational. In working on the "paradox of turnout," Bendor et al. addressed a key issue that long beguiled the RC literature. Notably, however, Bendor et al. confined their contributions to formal modeling. Thus, the pattern that has spread across the social sciences - where RC-based theories bring on board insights developed by behaviorists - has failed to fully materialize in the study of electoral accountability.

The primary finding that results from applying the behavioral methodology to the study of electoral accountability is that new institutions - in particular, the growth of the administrative state - appear to impede electoral accountability significantly. To be clear: delegation *as such* impedes accountability. To put the point differently: if citizens could cast votes for bureaucrats, delegation would still tend to insulate principals and leave agents "holding the bag." Likewise, the new tools that governments employ, such as nudging, can impede electoral accountability. The complexity wrought by delegation, and the indirectness wrought by soft paternalism, reduce the quality of individual judgments about blameworthiness. Fortunately, we can design institutions that debias these tendencies.

# Roadmap

Chapters 2 and 3 represent three efforts at testing RC-based theories of electoral accountability through randomized control trials. These studies take aim at concepts that are crucial to our understanding of a central feature driving retrospective evaluation of policy: blame. In study after study, blame has been shown to drive more political action than praise. Chapters 2 and 3 test how our evolving political system impacts blameworthiness judgments. In Chapter 2, I analyze how delegating policymaking authority changes blameworthiness judgments. And in Chapter 3, I analyze how soft paternalism, or nudging, changes assessments of blame.  
 
Chapter 4 operates a more theoretical level, but nonetheless retains its behavioral approach. Traditional EA depends on a rigid legal formalism. It assumes that, when laws change, behavior automatically changes. Chapter 4 rejects this formalist thinking. Instead, it offers an approach to law - and, in particular, legal change - that takes a more realistic, cognitive approach. This is a crucial development for studies of electoral accountability, since legal change *the* payoff of political accountability. Understanding when it works - and when it doesn't - is paramount. 

Chapter 5 offers a tentative model of electoral accountability that is consistent with the findings of the previous chapter. The primary result of Chapters 2 and 3 is that delegation and new legal tools, such as soft paternalism, inhibit individuals' ability to hold officials accountable for failed policies. The model presented in Chapter 5 accounts for these problems, and makes institutional recommendations to remedy them. If successful, the model of electoral accountability presented in Chapter 5 will ***
